export const endpoints = {
  login: 'store/auth/login/',
  refresh: 'store/auth/refresh/',
  restaurants: 'food/restaurants/',
  riderMe: 'food/rider/me/',
  vendorRestaurant: 'food/vendor/restaurant/',
  deviceRegister: 'food/devices/register/',
  deviceUnregister: 'food/devices/unregister/',
  riderPrivacy: 'food/rider/privacy/',
  mobileConfig: 'food/mobile/config/',
  notifications: 'food/notifications/',
  storeCategories: 'store/categories/',
  storeProducts: 'store/products/',
  storeProductDetail: (slug: string) => `store/products/${slug}/`,
  storeConfig: 'store/config/',
  storeCart: 'store/cart/',
  storeCartMerge: 'store/cart/merge/',
  storeOrders: 'store/orders/',
} as const;
